"""empty message

Revision ID: 03d654bdfa34
Revises: 8a93caa6b35c
Create Date: 2023-04-28 12:44:21.734876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d654bdfa34'
down_revision = '8a93caa6b35c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
