"""empty message

Revision ID: f96cc5737621
Revises: d1437bf3e001
Create Date: 2023-04-26 17:51:28.246760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96cc5737621'
down_revision = 'd1437bf3e001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
