"""empty message

Revision ID: fdf687c07b47
Revises: eaa778d40194
Create Date: 2023-04-27 02:18:35.555184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf687c07b47'
down_revision = 'eaa778d40194'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
